version: "3.7"

services:
  app:
    image: php:8.0-apache
    volumes:
      - ./:/var/www/html/
      - ./config/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 3000:80
